sudo: false
language: cpp

os:
  - linux

compiler:
  - gcc

git:
  depth: 1
  submodules: false

before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
    export CC=gcc-5 CXX=g++-5;
    fi

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - cmake
      - cmake-data
      - gcc-5
      - g++-5

install:
  - mkdir cestra_build
  - cd cestra_build
  - cmake ../ -DCMAKE_BUILD_TYPE=Release

before_script:
  - ${CXX} --version
  - ${CC} --version
  - cmake --version

script:
  - make
