if(WIN32)
    include(${CMAKE_SOURCE_DIR}/cmake/Platform/Windows.cmake)
elseif(UNIX)
    if(${CMAKE_SYSTEM_NAME} MATCHES "Linux") 
        include(${CMAKE_SOURCE_DIR}/cmake/Platform/Linux.cmake) 
    else()
        message(FATAL_ERROR "Platform not supported.") 
    endif()
else()
    message(FATAL_ERROR "Platform not supported.")
endif()
